---
# TODO: create CloudFormation template to create S3 bucket	
AWSTemplateFormatVersion: "2010-09-09"

Description: S3 Bucket exercise

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket 
    Properties:
       BucketName: learn-cloudformation-danielazacarias
